### ISSUE TITLE
如何获取data中的地理位置数据呢？

### ISSUE THREAD

**Issue by ManCioufan** [117503445/xdu_ncov_check_in#1]
我用fiddle抓包，结果发现疫情通提交的method是connect，解析不出那些数据。
所以想请教一下dalao如何获取data中的地理位置数据呢？

**Comment by 117503445** [comment]
我是直接在电脑上对 https://xxcapp.xidian.edu.cn/ncov/wap/default/index?from=history 进行抓包的.韩xy大佬去年写的工具 http://yqt.pescn.cc/ 里不需要用户提交地址信息,我觉得可能包里不发地理位置就是默认为上一次签到的地理位置.(没验证过
